spring:
  datasource:
    url: jdbc:postgresql://localhost:5001/primes
    username: postgres
    password: password
  devtools:
    restart:
      poll-interval: 2s

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  sql:
    init:
      mode: always
      continue-on-error: true



  rabbitmq:
    host: localhost
    port: 5003
    username: guest
    password: guest

server:
  port: 8085

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.springframework.jdbc.datasource.DriverManagerDataSource: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    com:
      zaxxer:
        hikari: DEBUG



