#
# To deploy:
#
# kubectl apply -f deploy.yaml
#
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prime-service
  template:
    metadata:
      labels:
        app: prime-service
    spec:
      containers: 
      - name: prime-service
        image: $CONTAINER_REGISTRY/prime-service:$VERSION
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "4000"
---
apiVersion: v1
kind: Service
metadata:
  name: prime-service
spec:
  selector:
    app: prime-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000