#
# To deploy:
#
# kubectl apply -f deploy.yaml
#
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prime-service
  template:
    metadata:
      labels:
        app: prime-service
    spec:
      containers: 
      - name: prime-service
        image: $CONTAINER_REGISTRY/prime-service:$VERSION
        imagePullPolicy: IfNotPresent
        env:
        - name: server.port
          value: "4001"
        - name: spring.datasource.url
          value: jdbc:postgresql://postgres-primes-service:5432/primes
        - name: spring.datasource.username
          value: postgres
        - name: spring.datasource.password
          value: password
        - name: spring.jpa.hibernate.ddl-auto
          value: update
---
apiVersion: v1
kind: Service
metadata:
  name: prime-service
spec:
  selector:
    app: prime-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001