#
# To deploy:
#
# kubectl apply -f deploy.yaml
#
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prime-service
  template:
    metadata:
      labels:
        app: prime-service
    spec:
      containers: 
      - name: prime-service
        image: $CONTAINER_REGISTRY/prime-service:$VERSION
        imagePullPolicy: IfNotPresent
        env:
        - name: server.port
          value: "4001"
        - name: spring.datasource.url
          value: jdbc:postgresql://p466-postgres-server.postgres.database.azure.com:5432/primes?sslmode=require
        - name: spring.datasource.username
          value: admin410
        - name: spring.datasource.password
          value: p466password321!

---
apiVersion: v1
kind: Service
metadata:
  name: prime-service
spec:
  selector:
    app: prime-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001