#
# To deploy:
#
# kubectl apply -f deploy.yaml
#
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prime-service
  template:
    metadata:
      labels:
        app: prime-service
    spec:
      containers: 
      - name: prime-service
        image: $CONTAINER_REGISTRY/prime-service:$VERSION
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"



---
apiVersion: v1
kind: Service
metadata:
  name: prime-service
spec:
  selector:
    app: prime-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-primes-secrets
stringData:
  SPRING_DATASOURCE_PASSWORD: $SPRING_DATASOURCE_PW
  SPRING_DATASOURCE_USERNAME: $SPRING_DATASOURCE_UN
  SPRING_DATASOURCE_URL: $SPRING_DATASOURCE_URL